/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_window1 (void)
{
  GtkWidget *window1;
  GtkWidget *fixed1;
  GtkWidget *entry1;
  GtkWidget *CE;
  GtkWidget *bksp;
  GtkWidget *CLR;
  GtkWidget *seven;
  GtkWidget *eight;
  GtkWidget *nine;
  GtkWidget *six;
  GtkWidget *two;
  GtkWidget *three;
  GtkWidget *mod;
  GtkWidget *zero;
  GtkWidget *decm;
  GtkWidget *equal;
  GtkWidget *add;
  GtkWidget *min;
  GtkWidget *mul;
  GtkWidget *div;
  GtkWidget *four;
  GtkWidget *five;
  GtkWidget *one;

  window1 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window1), _("window1"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (window1), fixed1);

  entry1 = gtk_entry_new ();
  gtk_widget_show (entry1);
  gtk_fixed_put (GTK_FIXED (fixed1), entry1, 152, 24);
  gtk_widget_set_size_request (entry1, 152, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry1), 8226);

  CE = gtk_button_new_with_mnemonic (_("CE"));
  gtk_widget_show (CE);
  gtk_fixed_put (GTK_FIXED (fixed1), CE, 96, 96);
  gtk_widget_set_size_request (CE, 69, 29);

  bksp = gtk_button_new_with_mnemonic (_("BKSP"));
  gtk_widget_show (bksp);
  gtk_fixed_put (GTK_FIXED (fixed1), bksp, 16, 96);
  gtk_widget_set_size_request (bksp, 70, 29);

  CLR = gtk_button_new_with_mnemonic (_("CLR"));
  gtk_widget_show (CLR);
  gtk_fixed_put (GTK_FIXED (fixed1), CLR, 176, 96);
  gtk_widget_set_size_request (CLR, 70, 29);

  seven = gtk_button_new_with_mnemonic (_("7"));
  gtk_widget_show (seven);
  gtk_fixed_put (GTK_FIXED (fixed1), seven, 16, 144);
  gtk_widget_set_size_request (seven, 70, 29);

  eight = gtk_button_new_with_mnemonic (_("8"));
  gtk_widget_show (eight);
  gtk_fixed_put (GTK_FIXED (fixed1), eight, 96, 144);
  gtk_widget_set_size_request (eight, 70, 29);

  nine = gtk_button_new_with_mnemonic (_("9"));
  gtk_widget_show (nine);
  gtk_fixed_put (GTK_FIXED (fixed1), nine, 184, 144);
  gtk_widget_set_size_request (nine, 69, 29);

  six = gtk_button_new_with_mnemonic (_("6"));
  gtk_widget_show (six);
  gtk_fixed_put (GTK_FIXED (fixed1), six, 192, 192);
  gtk_widget_set_size_request (six, 79, 29);

  two = gtk_button_new_with_mnemonic (_("2"));
  gtk_widget_show (two);
  gtk_fixed_put (GTK_FIXED (fixed1), two, 104, 240);
  gtk_widget_set_size_request (two, 79, 29);

  three = gtk_button_new_with_mnemonic (_("3"));
  gtk_widget_show (three);
  gtk_fixed_put (GTK_FIXED (fixed1), three, 192, 240);
  gtk_widget_set_size_request (three, 78, 29);

  mod = gtk_button_new_with_mnemonic (_("%"));
  gtk_widget_show (mod);
  gtk_fixed_put (GTK_FIXED (fixed1), mod, 256, 96);
  gtk_widget_set_size_request (mod, 69, 29);

  zero = gtk_button_new_with_mnemonic (_("0"));
  gtk_widget_show (zero);
  gtk_fixed_put (GTK_FIXED (fixed1), zero, 16, 288);
  gtk_widget_set_size_request (zero, 79, 29);

  decm = gtk_button_new_with_mnemonic (_("."));
  gtk_widget_show (decm);
  gtk_fixed_put (GTK_FIXED (fixed1), decm, 112, 288);
  gtk_widget_set_size_request (decm, 70, 29);

  equal = gtk_button_new_with_mnemonic (_("="));
  gtk_widget_show (equal);
  gtk_fixed_put (GTK_FIXED (fixed1), equal, 192, 288);
  gtk_widget_set_size_request (equal, 78, 29);

  add = gtk_button_new_with_mnemonic (_("+"));
  gtk_widget_show (add);
  gtk_fixed_put (GTK_FIXED (fixed1), add, 280, 288);
  gtk_widget_set_size_request (add, 78, 29);

  min = gtk_button_new_with_mnemonic (_("-"));
  gtk_widget_show (min);
  gtk_fixed_put (GTK_FIXED (fixed1), min, 280, 240);
  gtk_widget_set_size_request (min, 79, 29);

  mul = gtk_button_new_with_mnemonic (_("x"));
  gtk_widget_show (mul);
  gtk_fixed_put (GTK_FIXED (fixed1), mul, 280, 192);
  gtk_widget_set_size_request (mul, 79, 29);

  div = gtk_button_new_with_mnemonic (_("/"));
  gtk_widget_show (div);
  gtk_fixed_put (GTK_FIXED (fixed1), div, 264, 144);
  gtk_widget_set_size_request (div, 70, 29);

  four = gtk_button_new_with_mnemonic (_("4"));
  gtk_widget_show (four);
  gtk_fixed_put (GTK_FIXED (fixed1), four, 16, 192);
  gtk_widget_set_size_request (four, 79, 29);

  five = gtk_button_new_with_mnemonic (_("5"));
  gtk_widget_show (five);
  gtk_fixed_put (GTK_FIXED (fixed1), five, 104, 192);
  gtk_widget_set_size_request (five, 78, 29);

  one = gtk_button_new_with_mnemonic (_("1"));
  gtk_widget_show (one);
  gtk_fixed_put (GTK_FIXED (fixed1), one, 16, 240);
  gtk_widget_set_size_request (one, 79, 29);

  g_signal_connect ((gpointer) CE, "clicked",
                    G_CALLBACK (on_CE_clicked),
                    NULL);
  g_signal_connect ((gpointer) bksp, "clicked",
                    G_CALLBACK (on_bksp_clicked),
                    NULL);
  g_signal_connect ((gpointer) CLR, "clicked",
                    G_CALLBACK (on_CLR_clicked),
                    NULL);
  g_signal_connect ((gpointer) seven, "clicked",
                    G_CALLBACK (on_seven_clicked),
                    NULL);
  g_signal_connect ((gpointer) eight, "clicked",
                    G_CALLBACK (on_eight_clicked),
                    NULL);
  g_signal_connect ((gpointer) eight, "clicked",
                    G_CALLBACK (on_eight_clicked),
                    NULL);
  g_signal_connect ((gpointer) nine, "clicked",
                    G_CALLBACK (on_nine_clicked),
                    NULL);
  g_signal_connect ((gpointer) six, "clicked",
                    G_CALLBACK (on_six_clicked),
                    NULL);
  g_signal_connect ((gpointer) two, "clicked",
                    G_CALLBACK (on_two_clicked),
                    NULL);
  g_signal_connect ((gpointer) three, "clicked",
                    G_CALLBACK (on_three_clicked),
                    NULL);
  g_signal_connect ((gpointer) mod, "clicked",
                    G_CALLBACK (on_mod_clicked),
                    NULL);
  g_signal_connect ((gpointer) zero, "clicked",
                    G_CALLBACK (on_zero_clicked),
                    NULL);
  g_signal_connect ((gpointer) decm, "clicked",
                    G_CALLBACK (on_decm_clicked),
                    NULL);
  g_signal_connect ((gpointer) equal, "clicked",
                    G_CALLBACK (on_equal_clicked),
                    NULL);
  g_signal_connect ((gpointer) add, "clicked",
                    G_CALLBACK (on_add_clicked),
                    NULL);
  g_signal_connect ((gpointer) min, "clicked",
                    G_CALLBACK (on_min_clicked),
                    NULL);
  g_signal_connect ((gpointer) mul, "clicked",
                    G_CALLBACK (on_mul_clicked),
                    NULL);
  g_signal_connect ((gpointer) div, "clicked",
                    G_CALLBACK (on_div_clicked),
                    NULL);
  g_signal_connect ((gpointer) four, "clicked",
                    G_CALLBACK (on_four_clicked),
                    NULL);
  g_signal_connect ((gpointer) five, "clicked",
                    G_CALLBACK (on_five_clicked),
                    NULL);
  g_signal_connect ((gpointer) one, "clicked",
                    G_CALLBACK (on_one_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window1, window1, "window1");
  GLADE_HOOKUP_OBJECT (window1, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (window1, entry1, "entry1");
  GLADE_HOOKUP_OBJECT (window1, CE, "CE");
  GLADE_HOOKUP_OBJECT (window1, bksp, "bksp");
  GLADE_HOOKUP_OBJECT (window1, CLR, "CLR");
  GLADE_HOOKUP_OBJECT (window1, seven, "seven");
  GLADE_HOOKUP_OBJECT (window1, eight, "eight");
  GLADE_HOOKUP_OBJECT (window1, nine, "nine");
  GLADE_HOOKUP_OBJECT (window1, six, "six");
  GLADE_HOOKUP_OBJECT (window1, two, "two");
  GLADE_HOOKUP_OBJECT (window1, three, "three");
  GLADE_HOOKUP_OBJECT (window1, mod, "mod");
  GLADE_HOOKUP_OBJECT (window1, zero, "zero");
  GLADE_HOOKUP_OBJECT (window1, decm, "decm");
  GLADE_HOOKUP_OBJECT (window1, equal, "equal");
  GLADE_HOOKUP_OBJECT (window1, add, "add");
  GLADE_HOOKUP_OBJECT (window1, min, "min");
  GLADE_HOOKUP_OBJECT (window1, mul, "mul");
  GLADE_HOOKUP_OBJECT (window1, div, "div");
  GLADE_HOOKUP_OBJECT (window1, four, "four");
  GLADE_HOOKUP_OBJECT (window1, five, "five");
  GLADE_HOOKUP_OBJECT (window1, one, "one");

  return window1;
}

